// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/serverpb/api.proto

package serverpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TrxnRecord_TrxnType int32

const (
	TrxnRecord_Unknown TrxnRecord_TrxnType = 0
	TrxnRecord_Put     TrxnRecord_TrxnType = 1
	TrxnRecord_Delete  TrxnRecord_TrxnType = 2
)

var TrxnRecord_TrxnType_name = map[int32]string{
	0: "Unknown",
	1: "Put",
	2: "Delete",
}

var TrxnRecord_TrxnType_value = map[string]int32{
	"Unknown": 0,
	"Put":     1,
	"Delete":  2,
}

func (x TrxnRecord_TrxnType) String() string {
	return proto.EnumName(TrxnRecord_TrxnType_name, int32(x))
}

func (TrxnRecord_TrxnType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8ac913527469ef71, []int{12, 0}
}

type IterateRequest struct {
	// KeyPrefix can be used to iterate through keys that have this prefix.
	KeyPrefix []byte `protobuf:"bytes,1,opt,name=keyPrefix,proto3" json:"keyPrefix,omitempty"`
	// StartKey can be used to begin the iteration from the specified key.
	StartKey             []byte   `protobuf:"bytes,2,opt,name=startKey,proto3" json:"startKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IterateRequest) Reset()         { *m = IterateRequest{} }
func (m *IterateRequest) String() string { return proto.CompactTextString(m) }
func (*IterateRequest) ProtoMessage()    {}
func (*IterateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac913527469ef71, []int{0}
}

func (m *IterateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IterateRequest.Unmarshal(m, b)
}
func (m *IterateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IterateRequest.Marshal(b, m, deterministic)
}
func (m *IterateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IterateRequest.Merge(m, src)
}
func (m *IterateRequest) XXX_Size() int {
	return xxx_messageInfo_IterateRequest.Size(m)
}
func (m *IterateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IterateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IterateRequest proto.InternalMessageInfo

func (m *IterateRequest) GetKeyPrefix() []byte {
	if m != nil {
		return m.KeyPrefix
	}
	return nil
}

func (m *IterateRequest) GetStartKey() []byte {
	if m != nil {
		return m.StartKey
	}
	return nil
}

type IterateResponse struct {
	// Status captures any errors with the current iteration.
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Key of the current iteration.
	Key []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Value of the current iteration.
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IterateResponse) Reset()         { *m = IterateResponse{} }
func (m *IterateResponse) String() string { return proto.CompactTextString(m) }
func (*IterateResponse) ProtoMessage()    {}
func (*IterateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac913527469ef71, []int{1}
}

func (m *IterateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IterateResponse.Unmarshal(m, b)
}
func (m *IterateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IterateResponse.Marshal(b, m, deterministic)
}
func (m *IterateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IterateResponse.Merge(m, src)
}
func (m *IterateResponse) XXX_Size() int {
	return xxx_messageInfo_IterateResponse.Size(m)
}
func (m *IterateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IterateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IterateResponse proto.InternalMessageInfo

func (m *IterateResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *IterateResponse) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *IterateResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Status struct {
	// Code captures the error code of the underlying operation.
	// A non zero error code is considered to be a failure.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Message captures if any the error message of the failed operation.
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac913527469ef71, []int{2}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PutRequest struct {
	// Key is the key, in bytes, to put into the key value store.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Value is the value, in bytes, to associate with the key in the key value store.
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac913527469ef71, []int{3}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PutResponse struct {
	// Status indicates the result of the Put operation
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac913527469ef71, []int{4}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetRequest struct {
	// Key is the key, in bytes, whose associated value is loaded from the key value store.
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac913527469ef71, []int{5}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetResponse struct {
	// Status indicates the result of the Get operation
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Value is the value, in bytes, that is associated with the given key in the key value store.
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac913527469ef71, []int{6}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type MultiGetRequest struct {
	// Keys is the collection of keys whose values are returned from the bulk Get operation.
	Keys                 [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiGetRequest) Reset()         { *m = MultiGetRequest{} }
func (m *MultiGetRequest) String() string { return proto.CompactTextString(m) }
func (*MultiGetRequest) ProtoMessage()    {}
func (*MultiGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac913527469ef71, []int{7}
}

func (m *MultiGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiGetRequest.Unmarshal(m, b)
}
func (m *MultiGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiGetRequest.Marshal(b, m, deterministic)
}
func (m *MultiGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiGetRequest.Merge(m, src)
}
func (m *MultiGetRequest) XXX_Size() int {
	return xxx_messageInfo_MultiGetRequest.Size(m)
}
func (m *MultiGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MultiGetRequest proto.InternalMessageInfo

func (m *MultiGetRequest) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

type MultiGetResponse struct {
	// Status indicates the result of the bulk Get operation
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Values are the individual responses of the bulk Get operation.
	Values               [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiGetResponse) Reset()         { *m = MultiGetResponse{} }
func (m *MultiGetResponse) String() string { return proto.CompactTextString(m) }
func (*MultiGetResponse) ProtoMessage()    {}
func (*MultiGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac913527469ef71, []int{8}
}

func (m *MultiGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiGetResponse.Unmarshal(m, b)
}
func (m *MultiGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiGetResponse.Marshal(b, m, deterministic)
}
func (m *MultiGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiGetResponse.Merge(m, src)
}
func (m *MultiGetResponse) XXX_Size() int {
	return xxx_messageInfo_MultiGetResponse.Size(m)
}
func (m *MultiGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MultiGetResponse proto.InternalMessageInfo

func (m *MultiGetResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *MultiGetResponse) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

type GetChangesRequest struct {
	// FromChangeNumber is the starting change number from which to retrieve changes
	FromChangeNumber uint64 `protobuf:"varint,1,opt,name=fromChangeNumber,proto3" json:"fromChangeNumber,omitempty"`
	// MaxNumberOfChanges is the maximum number of changes to return from this invocation
	MaxNumberOfChanges   uint32   `protobuf:"varint,2,opt,name=maxNumberOfChanges,proto3" json:"maxNumberOfChanges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChangesRequest) Reset()         { *m = GetChangesRequest{} }
func (m *GetChangesRequest) String() string { return proto.CompactTextString(m) }
func (*GetChangesRequest) ProtoMessage()    {}
func (*GetChangesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac913527469ef71, []int{9}
}

func (m *GetChangesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChangesRequest.Unmarshal(m, b)
}
func (m *GetChangesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChangesRequest.Marshal(b, m, deterministic)
}
func (m *GetChangesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChangesRequest.Merge(m, src)
}
func (m *GetChangesRequest) XXX_Size() int {
	return xxx_messageInfo_GetChangesRequest.Size(m)
}
func (m *GetChangesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChangesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChangesRequest proto.InternalMessageInfo

func (m *GetChangesRequest) GetFromChangeNumber() uint64 {
	if m != nil {
		return m.FromChangeNumber
	}
	return 0
}

func (m *GetChangesRequest) GetMaxNumberOfChanges() uint32 {
	if m != nil {
		return m.MaxNumberOfChanges
	}
	return 0
}

type GetChangesResponse struct {
	// Status indicates the result of the GetChanges operation
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// MasterChangeNumber indicates the latest change number on master node
	MasterChangeNumber uint64 `protobuf:"varint,2,opt,name=masterChangeNumber,proto3" json:"masterChangeNumber,omitempty"`
	// NumberOfChanges indicates the number of change records in the response
	NumberOfChanges uint32 `protobuf:"varint,3,opt,name=numberOfChanges,proto3" json:"numberOfChanges,omitempty"`
	// Changes is the collection of change records
	Changes              []*ChangeRecord `protobuf:"bytes,4,rep,name=changes,proto3" json:"changes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetChangesResponse) Reset()         { *m = GetChangesResponse{} }
func (m *GetChangesResponse) String() string { return proto.CompactTextString(m) }
func (*GetChangesResponse) ProtoMessage()    {}
func (*GetChangesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac913527469ef71, []int{10}
}

func (m *GetChangesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChangesResponse.Unmarshal(m, b)
}
func (m *GetChangesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChangesResponse.Marshal(b, m, deterministic)
}
func (m *GetChangesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChangesResponse.Merge(m, src)
}
func (m *GetChangesResponse) XXX_Size() int {
	return xxx_messageInfo_GetChangesResponse.Size(m)
}
func (m *GetChangesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChangesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetChangesResponse proto.InternalMessageInfo

func (m *GetChangesResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetChangesResponse) GetMasterChangeNumber() uint64 {
	if m != nil {
		return m.MasterChangeNumber
	}
	return 0
}

func (m *GetChangesResponse) GetNumberOfChanges() uint32 {
	if m != nil {
		return m.NumberOfChanges
	}
	return 0
}

func (m *GetChangesResponse) GetChanges() []*ChangeRecord {
	if m != nil {
		return m.Changes
	}
	return nil
}

type ChangeRecord struct {
	// SerialisedForm is the internal byte array representation of this change record
	SerialisedForm []byte `protobuf:"bytes,1,opt,name=serialisedForm,proto3" json:"serialisedForm,omitempty"`
	// ChangeNumber indicates the change number of this change record
	ChangeNumber uint64 `protobuf:"varint,2,opt,name=changeNumber,proto3" json:"changeNumber,omitempty"`
	// NumberOfTrxns indicates the number of transactions associated with this change record
	NumberOfTrxns uint32 `protobuf:"varint,3,opt,name=numberOfTrxns,proto3" json:"numberOfTrxns,omitempty"`
	// Trxns is the collection of transaction records associated with this change record
	Trxns                []*TrxnRecord `protobuf:"bytes,4,rep,name=trxns,proto3" json:"trxns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ChangeRecord) Reset()         { *m = ChangeRecord{} }
func (m *ChangeRecord) String() string { return proto.CompactTextString(m) }
func (*ChangeRecord) ProtoMessage()    {}
func (*ChangeRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac913527469ef71, []int{11}
}

func (m *ChangeRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeRecord.Unmarshal(m, b)
}
func (m *ChangeRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeRecord.Marshal(b, m, deterministic)
}
func (m *ChangeRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeRecord.Merge(m, src)
}
func (m *ChangeRecord) XXX_Size() int {
	return xxx_messageInfo_ChangeRecord.Size(m)
}
func (m *ChangeRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeRecord proto.InternalMessageInfo

func (m *ChangeRecord) GetSerialisedForm() []byte {
	if m != nil {
		return m.SerialisedForm
	}
	return nil
}

func (m *ChangeRecord) GetChangeNumber() uint64 {
	if m != nil {
		return m.ChangeNumber
	}
	return 0
}

func (m *ChangeRecord) GetNumberOfTrxns() uint32 {
	if m != nil {
		return m.NumberOfTrxns
	}
	return 0
}

func (m *ChangeRecord) GetTrxns() []*TrxnRecord {
	if m != nil {
		return m.Trxns
	}
	return nil
}

type TrxnRecord struct {
	// Type indicates the type of this transaction - Put, Delete, etc.
	Type TrxnRecord_TrxnType `protobuf:"varint,1,opt,name=type,proto3,enum=dkv.serverpb.TrxnRecord_TrxnType" json:"type,omitempty"`
	// Key is the byte array representation of the key associated with this transaction
	Key []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Value is the byte array representation of the value associated with this transaction
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrxnRecord) Reset()         { *m = TrxnRecord{} }
func (m *TrxnRecord) String() string { return proto.CompactTextString(m) }
func (*TrxnRecord) ProtoMessage()    {}
func (*TrxnRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac913527469ef71, []int{12}
}

func (m *TrxnRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrxnRecord.Unmarshal(m, b)
}
func (m *TrxnRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrxnRecord.Marshal(b, m, deterministic)
}
func (m *TrxnRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrxnRecord.Merge(m, src)
}
func (m *TrxnRecord) XXX_Size() int {
	return xxx_messageInfo_TrxnRecord.Size(m)
}
func (m *TrxnRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_TrxnRecord.DiscardUnknown(m)
}

var xxx_messageInfo_TrxnRecord proto.InternalMessageInfo

func (m *TrxnRecord) GetType() TrxnRecord_TrxnType {
	if m != nil {
		return m.Type
	}
	return TrxnRecord_Unknown
}

func (m *TrxnRecord) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *TrxnRecord) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type BackupRequest struct {
	// BackupPath indicates a filesystem folder or file used for backing up the keyspace.
	BackupPath           string   `protobuf:"bytes,1,opt,name=backupPath,proto3" json:"backupPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupRequest) Reset()         { *m = BackupRequest{} }
func (m *BackupRequest) String() string { return proto.CompactTextString(m) }
func (*BackupRequest) ProtoMessage()    {}
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac913527469ef71, []int{13}
}

func (m *BackupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupRequest.Unmarshal(m, b)
}
func (m *BackupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupRequest.Marshal(b, m, deterministic)
}
func (m *BackupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupRequest.Merge(m, src)
}
func (m *BackupRequest) XXX_Size() int {
	return xxx_messageInfo_BackupRequest.Size(m)
}
func (m *BackupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackupRequest proto.InternalMessageInfo

func (m *BackupRequest) GetBackupPath() string {
	if m != nil {
		return m.BackupPath
	}
	return ""
}

type RestoreRequest struct {
	// RestorePath indicates a filesystem folder or file used for restoring the keyspace.
	RestorePath          string   `protobuf:"bytes,1,opt,name=restorePath,proto3" json:"restorePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreRequest) Reset()         { *m = RestoreRequest{} }
func (m *RestoreRequest) String() string { return proto.CompactTextString(m) }
func (*RestoreRequest) ProtoMessage()    {}
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac913527469ef71, []int{14}
}

func (m *RestoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreRequest.Unmarshal(m, b)
}
func (m *RestoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreRequest.Marshal(b, m, deterministic)
}
func (m *RestoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreRequest.Merge(m, src)
}
func (m *RestoreRequest) XXX_Size() int {
	return xxx_messageInfo_RestoreRequest.Size(m)
}
func (m *RestoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreRequest proto.InternalMessageInfo

func (m *RestoreRequest) GetRestorePath() string {
	if m != nil {
		return m.RestorePath
	}
	return ""
}

type AddNodeRequest struct {
	// NodeId represents the identifier of the node that needs to
	// be added to the cluster.
	NodeId uint32 `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	// NodeUrl represents the URL for the Nexus service running on
	// the node that needs to be added to the cluster. Other Nexus
	// peers communicate with this node on this service.
	NodeUrl              string   `protobuf:"bytes,2,opt,name=nodeUrl,proto3" json:"nodeUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNodeRequest) Reset()         { *m = AddNodeRequest{} }
func (m *AddNodeRequest) String() string { return proto.CompactTextString(m) }
func (*AddNodeRequest) ProtoMessage()    {}
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac913527469ef71, []int{15}
}

func (m *AddNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeRequest.Unmarshal(m, b)
}
func (m *AddNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeRequest.Marshal(b, m, deterministic)
}
func (m *AddNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeRequest.Merge(m, src)
}
func (m *AddNodeRequest) XXX_Size() int {
	return xxx_messageInfo_AddNodeRequest.Size(m)
}
func (m *AddNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeRequest proto.InternalMessageInfo

func (m *AddNodeRequest) GetNodeId() uint32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *AddNodeRequest) GetNodeUrl() string {
	if m != nil {
		return m.NodeUrl
	}
	return ""
}

type RemoveNodeRequest struct {
	// NodeId represents the identifier of the node that needs to
	// be removed from the cluster.
	NodeId               uint32   `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveNodeRequest) Reset()         { *m = RemoveNodeRequest{} }
func (m *RemoveNodeRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveNodeRequest) ProtoMessage()    {}
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac913527469ef71, []int{16}
}

func (m *RemoveNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveNodeRequest.Unmarshal(m, b)
}
func (m *RemoveNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveNodeRequest.Marshal(b, m, deterministic)
}
func (m *RemoveNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveNodeRequest.Merge(m, src)
}
func (m *RemoveNodeRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveNodeRequest.Size(m)
}
func (m *RemoveNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveNodeRequest proto.InternalMessageInfo

func (m *RemoveNodeRequest) GetNodeId() uint32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func init() {
	proto.RegisterEnum("dkv.serverpb.TrxnRecord_TrxnType", TrxnRecord_TrxnType_name, TrxnRecord_TrxnType_value)
	proto.RegisterType((*IterateRequest)(nil), "dkv.serverpb.IterateRequest")
	proto.RegisterType((*IterateResponse)(nil), "dkv.serverpb.IterateResponse")
	proto.RegisterType((*Status)(nil), "dkv.serverpb.Status")
	proto.RegisterType((*PutRequest)(nil), "dkv.serverpb.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "dkv.serverpb.PutResponse")
	proto.RegisterType((*GetRequest)(nil), "dkv.serverpb.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "dkv.serverpb.GetResponse")
	proto.RegisterType((*MultiGetRequest)(nil), "dkv.serverpb.MultiGetRequest")
	proto.RegisterType((*MultiGetResponse)(nil), "dkv.serverpb.MultiGetResponse")
	proto.RegisterType((*GetChangesRequest)(nil), "dkv.serverpb.GetChangesRequest")
	proto.RegisterType((*GetChangesResponse)(nil), "dkv.serverpb.GetChangesResponse")
	proto.RegisterType((*ChangeRecord)(nil), "dkv.serverpb.ChangeRecord")
	proto.RegisterType((*TrxnRecord)(nil), "dkv.serverpb.TrxnRecord")
	proto.RegisterType((*BackupRequest)(nil), "dkv.serverpb.BackupRequest")
	proto.RegisterType((*RestoreRequest)(nil), "dkv.serverpb.RestoreRequest")
	proto.RegisterType((*AddNodeRequest)(nil), "dkv.serverpb.AddNodeRequest")
	proto.RegisterType((*RemoveNodeRequest)(nil), "dkv.serverpb.RemoveNodeRequest")
}

func init() { proto.RegisterFile("pkg/serverpb/api.proto", fileDescriptor_8ac913527469ef71) }

var fileDescriptor_8ac913527469ef71 = []byte{
	// 795 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x6e, 0xda, 0x48,
	0x14, 0x5e, 0x63, 0x02, 0xe4, 0xf0, 0x13, 0x32, 0x8a, 0x22, 0x96, 0x4d, 0xb2, 0xec, 0x68, 0x77,
	0x85, 0x76, 0x23, 0x52, 0xb9, 0x69, 0x2f, 0x12, 0xf5, 0xa2, 0x09, 0x6a, 0x9a, 0xa2, 0x26, 0x74,
	0x9a, 0xa0, 0xaa, 0x77, 0x06, 0x9f, 0x10, 0x04, 0xd8, 0xee, 0x78, 0x4c, 0xc3, 0x4b, 0x54, 0x55,
	0xef, 0xfa, 0x16, 0x7d, 0x96, 0x3e, 0x51, 0xc5, 0xd8, 0x06, 0xdb, 0x18, 0x29, 0xe2, 0x6e, 0xe6,
	0x3b, 0xe7, 0x7c, 0xe7, 0x3b, 0xe6, 0xf8, 0x33, 0xb0, 0x6b, 0x0f, 0xfb, 0x47, 0x0e, 0xf2, 0x09,
	0x72, 0xbb, 0x7b, 0xa4, 0xdb, 0x83, 0x86, 0xcd, 0x2d, 0x61, 0x91, 0x82, 0x31, 0x9c, 0x34, 0x02,
	0x9c, 0xbe, 0x81, 0xd2, 0xa5, 0x40, 0xae, 0x0b, 0x64, 0xf8, 0xc9, 0x45, 0x47, 0x90, 0x3d, 0xd8,
	0x1c, 0xe2, 0xb4, 0xcd, 0xf1, 0x6e, 0xf0, 0x50, 0x51, 0x6a, 0x4a, 0xbd, 0xc0, 0x16, 0x00, 0xa9,
	0x42, 0xce, 0x11, 0x3a, 0x17, 0x2d, 0x9c, 0x56, 0x52, 0x32, 0x38, 0xbf, 0xd3, 0x3e, 0x6c, 0xcd,
	0xb9, 0x1c, 0xdb, 0x32, 0x1d, 0x24, 0x87, 0x90, 0x71, 0x84, 0x2e, 0x5c, 0x47, 0x32, 0xe5, 0xb5,
	0x9d, 0x46, 0xb8, 0x7b, 0xe3, 0xbd, 0x8c, 0x31, 0x3f, 0x87, 0x94, 0x41, 0x1d, 0xce, 0x79, 0x67,
	0x47, 0xb2, 0x03, 0x1b, 0x13, 0x7d, 0xe4, 0x62, 0x45, 0x95, 0x98, 0x77, 0xa1, 0xcf, 0x21, 0xe3,
	0x55, 0x12, 0x02, 0xe9, 0x9e, 0x65, 0xa0, 0x64, 0xdf, 0x60, 0xf2, 0x4c, 0x2a, 0x90, 0x1d, 0xa3,
	0xe3, 0xe8, 0x7d, 0x94, 0x4c, 0x9b, 0x2c, 0xb8, 0xd2, 0x63, 0x80, 0xb6, 0x2b, 0x82, 0x41, 0xfd,
	0x6e, 0x4a, 0x42, 0xb7, 0x54, 0xb8, 0xdb, 0x29, 0xe4, 0x65, 0xd5, 0x3a, 0x23, 0xd1, 0x03, 0x80,
	0x0b, 0x5c, 0xdd, 0x92, 0xbe, 0x83, 0xbc, 0x8c, 0xaf, 0xf5, 0xbc, 0x92, 0xf5, 0xfe, 0x03, 0x5b,
	0x6f, 0xdd, 0x91, 0x18, 0x84, 0xfa, 0x12, 0x48, 0x0f, 0x71, 0x3a, 0x23, 0x55, 0xeb, 0x05, 0x26,
	0xcf, 0xf4, 0x03, 0x94, 0x17, 0x69, 0x6b, 0xb5, 0xdf, 0x85, 0x8c, 0xec, 0xe8, 0x54, 0x52, 0x92,
	0xd7, 0xbf, 0x51, 0x0b, 0xb6, 0x2f, 0x50, 0x9c, 0xdf, 0xeb, 0x66, 0x1f, 0x9d, 0x40, 0xc2, 0x7f,
	0x50, 0xbe, 0xe3, 0xd6, 0xd8, 0x43, 0xaf, 0xdc, 0x71, 0x17, 0xb9, 0x6c, 0x92, 0x66, 0x4b, 0x38,
	0x69, 0x00, 0x19, 0xeb, 0x0f, 0xde, 0xe5, 0xfa, 0xce, 0x27, 0x92, 0x43, 0x16, 0x59, 0x42, 0x84,
	0xfe, 0x54, 0x80, 0x84, 0x3b, 0xae, 0x35, 0x8d, 0x6c, 0xea, 0x08, 0xe4, 0x11, 0x89, 0x29, 0x29,
	0x31, 0x21, 0x42, 0xea, 0xb0, 0x65, 0xc6, 0x14, 0xaa, 0x52, 0x61, 0x1c, 0x26, 0xc7, 0x90, 0xed,
	0xf9, 0x19, 0xe9, 0x9a, 0x5a, 0xcf, 0x6b, 0xd5, 0xa8, 0x10, 0x2f, 0x8f, 0x61, 0xcf, 0xe2, 0x06,
	0x0b, 0x52, 0xe9, 0x0f, 0x05, 0x0a, 0xe1, 0x08, 0xf9, 0x17, 0x4a, 0x0e, 0xf2, 0x81, 0x3e, 0x1a,
	0x38, 0x68, 0xbc, 0xb2, 0xf8, 0xd8, 0xdf, 0xa3, 0x18, 0x4a, 0x28, 0x14, 0x7a, 0xcb, 0x23, 0x44,
	0x30, 0xf2, 0x37, 0x14, 0x03, 0x95, 0x37, 0xfc, 0xc1, 0x0c, 0xa4, 0x47, 0x41, 0xd2, 0x80, 0x0d,
	0x21, 0xa3, 0x9e, 0xec, 0x4a, 0x54, 0xf6, 0x2c, 0xc7, 0x17, 0xed, 0xa5, 0xd1, 0xef, 0x0a, 0xc0,
	0x02, 0x25, 0xcf, 0x20, 0x2d, 0xa6, 0xb6, 0xf7, 0x72, 0x96, 0xb4, 0xbf, 0x56, 0x55, 0xcb, 0xe3,
	0xcd, 0xd4, 0x46, 0x26, 0xd3, 0x1f, 0xed, 0x02, 0x87, 0x90, 0x0b, 0x2a, 0x49, 0x1e, 0xb2, 0xb7,
	0xe6, 0xd0, 0xb4, 0x3e, 0x9b, 0xe5, 0xdf, 0x48, 0x16, 0xd4, 0xb6, 0x2b, 0xca, 0x0a, 0x01, 0xc8,
	0x34, 0x71, 0x84, 0x02, 0xcb, 0x29, 0x7a, 0x04, 0xc5, 0x33, 0xbd, 0x37, 0x74, 0xed, 0x60, 0x21,
	0x0f, 0x00, 0xba, 0x12, 0x68, 0xeb, 0xe2, 0x5e, 0x6a, 0xdc, 0x64, 0x21, 0x84, 0x6a, 0x50, 0x62,
	0xe8, 0x08, 0x8b, 0xcf, 0x9d, 0xb1, 0x06, 0x79, 0xee, 0x21, 0xa1, 0x92, 0x30, 0x44, 0xcf, 0xa0,
	0xf4, 0xd2, 0x30, 0xae, 0x2c, 0x63, 0x5e, 0xb3, 0x0b, 0x19, 0xd3, 0x32, 0xf0, 0xd2, 0x90, 0xe9,
	0x45, 0xe6, 0xdf, 0x66, 0x26, 0x35, 0x3b, 0xdd, 0xf2, 0x51, 0x60, 0x52, 0xfe, 0x95, 0xfe, 0x0f,
	0xdb, 0x0c, 0xc7, 0xd6, 0x04, 0x1f, 0x41, 0xa3, 0x7d, 0x4b, 0x81, 0xda, 0x6c, 0x75, 0xc8, 0x89,
	0x1c, 0x99, 0xc4, 0x7e, 0xa1, 0x85, 0xd9, 0x55, 0x7f, 0x4f, 0x88, 0xf8, 0xaf, 0xc9, 0x09, 0xa8,
	0x17, 0xb8, 0x54, 0xbb, 0x70, 0x8f, 0x78, 0x6d, 0xd8, 0x30, 0x2e, 0x21, 0x17, 0x98, 0x08, 0xd9,
	0x8f, 0xa6, 0xc5, 0x3c, 0xa8, 0x7a, 0xb0, 0x2a, 0xec, 0x53, 0xbd, 0x86, 0xac, 0xff, 0xf5, 0x20,
	0x7b, 0xd1, 0xd4, 0xe8, 0x07, 0xaa, 0xba, 0xbf, 0x22, 0xea, 0xf1, 0x3c, 0x51, 0x34, 0x1d, 0x4a,
	0xcd, 0x56, 0x87, 0xa1, 0x3d, 0x1a, 0xf4, 0x74, 0x31, 0xb0, 0x4c, 0x72, 0x2d, 0x5d, 0x38, 0x78,
	0x1f, 0xff, 0x5c, 0x9a, 0x27, 0xea, 0x55, 0xd5, 0xda, 0xea, 0x04, 0xaf, 0x89, 0xf6, 0x45, 0x81,
	0x72, 0xb3, 0xd5, 0x09, 0x36, 0x4a, 0x6e, 0x00, 0x39, 0x85, 0x8c, 0x07, 0x90, 0x3f, 0xa2, 0x04,
	0x91, 0xc5, 0xab, 0x26, 0xda, 0x10, 0x79, 0x01, 0xd9, 0x80, 0x27, 0x36, 0x7e, 0x74, 0x0b, 0x93,
	0xcb, 0xb5, 0xaf, 0x0a, 0x40, 0xb3, 0xd5, 0x39, 0x1f, 0xb9, 0x33, 0xa3, 0x9a, 0xb1, 0xf9, 0x8b,
	0x18, 0x67, 0x8b, 0xee, 0xe7, 0x0a, 0x31, 0xe7, 0x00, 0x8b, 0x1d, 0x8c, 0x3f, 0xaf, 0xa5, 0xed,
	0x4c, 0x26, 0x39, 0x83, 0x8f, 0xb9, 0x00, 0xea, 0x66, 0xe4, 0x7f, 0x8f, 0xa7, 0xbf, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x05, 0x48, 0x63, 0x8a, 0x95, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DKVClient is the client API for DKV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DKVClient interface {
	// Put puts the given key into the key value store
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	// Get gets the value associated with the given key from the key value store
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// MultiGet gets the values associated with given keys from the key value store
	MultiGet(ctx context.Context, in *MultiGetRequest, opts ...grpc.CallOption) (*MultiGetResponse, error)
	// Iterate iterates through the entire keyspace in no particular order and
	// returns the results as a stream of key value pairs
	Iterate(ctx context.Context, in *IterateRequest, opts ...grpc.CallOption) (DKV_IterateClient, error)
}

type dKVClient struct {
	cc *grpc.ClientConn
}

func NewDKVClient(cc *grpc.ClientConn) DKVClient {
	return &dKVClient{cc}
}

func (c *dKVClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, "/dkv.serverpb.DKV/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dKVClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/dkv.serverpb.DKV/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dKVClient) MultiGet(ctx context.Context, in *MultiGetRequest, opts ...grpc.CallOption) (*MultiGetResponse, error) {
	out := new(MultiGetResponse)
	err := c.cc.Invoke(ctx, "/dkv.serverpb.DKV/MultiGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dKVClient) Iterate(ctx context.Context, in *IterateRequest, opts ...grpc.CallOption) (DKV_IterateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DKV_serviceDesc.Streams[0], "/dkv.serverpb.DKV/Iterate", opts...)
	if err != nil {
		return nil, err
	}
	x := &dKVIterateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DKV_IterateClient interface {
	Recv() (*IterateResponse, error)
	grpc.ClientStream
}

type dKVIterateClient struct {
	grpc.ClientStream
}

func (x *dKVIterateClient) Recv() (*IterateResponse, error) {
	m := new(IterateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DKVServer is the server API for DKV service.
type DKVServer interface {
	// Put puts the given key into the key value store
	Put(context.Context, *PutRequest) (*PutResponse, error)
	// Get gets the value associated with the given key from the key value store
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// MultiGet gets the values associated with given keys from the key value store
	MultiGet(context.Context, *MultiGetRequest) (*MultiGetResponse, error)
	// Iterate iterates through the entire keyspace in no particular order and
	// returns the results as a stream of key value pairs
	Iterate(*IterateRequest, DKV_IterateServer) error
}

// UnimplementedDKVServer can be embedded to have forward compatible implementations.
type UnimplementedDKVServer struct {
}

func (*UnimplementedDKVServer) Put(ctx context.Context, req *PutRequest) (*PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (*UnimplementedDKVServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedDKVServer) MultiGet(ctx context.Context, req *MultiGetRequest) (*MultiGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiGet not implemented")
}
func (*UnimplementedDKVServer) Iterate(req *IterateRequest, srv DKV_IterateServer) error {
	return status.Errorf(codes.Unimplemented, "method Iterate not implemented")
}

func RegisterDKVServer(s *grpc.Server, srv DKVServer) {
	s.RegisterService(&_DKV_serviceDesc, srv)
}

func _DKV_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKVServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dkv.serverpb.DKV/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKVServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DKV_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKVServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dkv.serverpb.DKV/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKVServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DKV_MultiGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKVServer).MultiGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dkv.serverpb.DKV/MultiGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKVServer).MultiGet(ctx, req.(*MultiGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DKV_Iterate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(IterateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DKVServer).Iterate(m, &dKVIterateServer{stream})
}

type DKV_IterateServer interface {
	Send(*IterateResponse) error
	grpc.ServerStream
}

type dKVIterateServer struct {
	grpc.ServerStream
}

func (x *dKVIterateServer) Send(m *IterateResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _DKV_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dkv.serverpb.DKV",
	HandlerType: (*DKVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _DKV_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DKV_Get_Handler,
		},
		{
			MethodName: "MultiGet",
			Handler:    _DKV_MultiGet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Iterate",
			Handler:       _DKV_Iterate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/serverpb/api.proto",
}

// DKVReplicationClient is the client API for DKVReplication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DKVReplicationClient interface {
	// GetChanges retrieves all changes from a given change number
	GetChanges(ctx context.Context, in *GetChangesRequest, opts ...grpc.CallOption) (*GetChangesResponse, error)
}

type dKVReplicationClient struct {
	cc *grpc.ClientConn
}

func NewDKVReplicationClient(cc *grpc.ClientConn) DKVReplicationClient {
	return &dKVReplicationClient{cc}
}

func (c *dKVReplicationClient) GetChanges(ctx context.Context, in *GetChangesRequest, opts ...grpc.CallOption) (*GetChangesResponse, error) {
	out := new(GetChangesResponse)
	err := c.cc.Invoke(ctx, "/dkv.serverpb.DKVReplication/GetChanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DKVReplicationServer is the server API for DKVReplication service.
type DKVReplicationServer interface {
	// GetChanges retrieves all changes from a given change number
	GetChanges(context.Context, *GetChangesRequest) (*GetChangesResponse, error)
}

// UnimplementedDKVReplicationServer can be embedded to have forward compatible implementations.
type UnimplementedDKVReplicationServer struct {
}

func (*UnimplementedDKVReplicationServer) GetChanges(ctx context.Context, req *GetChangesRequest) (*GetChangesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChanges not implemented")
}

func RegisterDKVReplicationServer(s *grpc.Server, srv DKVReplicationServer) {
	s.RegisterService(&_DKVReplication_serviceDesc, srv)
}

func _DKVReplication_GetChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKVReplicationServer).GetChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dkv.serverpb.DKVReplication/GetChanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKVReplicationServer).GetChanges(ctx, req.(*GetChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DKVReplication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dkv.serverpb.DKVReplication",
	HandlerType: (*DKVReplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChanges",
			Handler:    _DKVReplication_GetChanges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/serverpb/api.proto",
}

// DKVBackupRestoreClient is the client API for DKVBackupRestore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DKVBackupRestoreClient interface {
	// Backup backs up the entire keyspace into the given filesystem location.
	Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*Status, error)
	// Restore restores the entire keyspace from an existing backup at the
	// given filesystem location.
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*Status, error)
}

type dKVBackupRestoreClient struct {
	cc *grpc.ClientConn
}

func NewDKVBackupRestoreClient(cc *grpc.ClientConn) DKVBackupRestoreClient {
	return &dKVBackupRestoreClient{cc}
}

func (c *dKVBackupRestoreClient) Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/dkv.serverpb.DKVBackupRestore/Backup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dKVBackupRestoreClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/dkv.serverpb.DKVBackupRestore/Restore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DKVBackupRestoreServer is the server API for DKVBackupRestore service.
type DKVBackupRestoreServer interface {
	// Backup backs up the entire keyspace into the given filesystem location.
	Backup(context.Context, *BackupRequest) (*Status, error)
	// Restore restores the entire keyspace from an existing backup at the
	// given filesystem location.
	Restore(context.Context, *RestoreRequest) (*Status, error)
}

// UnimplementedDKVBackupRestoreServer can be embedded to have forward compatible implementations.
type UnimplementedDKVBackupRestoreServer struct {
}

func (*UnimplementedDKVBackupRestoreServer) Backup(ctx context.Context, req *BackupRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Backup not implemented")
}
func (*UnimplementedDKVBackupRestoreServer) Restore(ctx context.Context, req *RestoreRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}

func RegisterDKVBackupRestoreServer(s *grpc.Server, srv DKVBackupRestoreServer) {
	s.RegisterService(&_DKVBackupRestore_serviceDesc, srv)
}

func _DKVBackupRestore_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKVBackupRestoreServer).Backup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dkv.serverpb.DKVBackupRestore/Backup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKVBackupRestoreServer).Backup(ctx, req.(*BackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DKVBackupRestore_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKVBackupRestoreServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dkv.serverpb.DKVBackupRestore/Restore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKVBackupRestoreServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DKVBackupRestore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dkv.serverpb.DKVBackupRestore",
	HandlerType: (*DKVBackupRestoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Backup",
			Handler:    _DKVBackupRestore_Backup_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _DKVBackupRestore_Restore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/serverpb/api.proto",
}

// DKVClusterClient is the client API for DKVCluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DKVClusterClient interface {
	// AddNode adds the given DKV node to the cluster that the
	// current node is a member of.
	AddNode(ctx context.Context, in *AddNodeRequest, opts ...grpc.CallOption) (*Status, error)
	// RemoveNode removes the given DKV node from the cluster that
	// the current node is a member of.
	RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*Status, error)
}

type dKVClusterClient struct {
	cc *grpc.ClientConn
}

func NewDKVClusterClient(cc *grpc.ClientConn) DKVClusterClient {
	return &dKVClusterClient{cc}
}

func (c *dKVClusterClient) AddNode(ctx context.Context, in *AddNodeRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/dkv.serverpb.DKVCluster/AddNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dKVClusterClient) RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/dkv.serverpb.DKVCluster/RemoveNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DKVClusterServer is the server API for DKVCluster service.
type DKVClusterServer interface {
	// AddNode adds the given DKV node to the cluster that the
	// current node is a member of.
	AddNode(context.Context, *AddNodeRequest) (*Status, error)
	// RemoveNode removes the given DKV node from the cluster that
	// the current node is a member of.
	RemoveNode(context.Context, *RemoveNodeRequest) (*Status, error)
}

// UnimplementedDKVClusterServer can be embedded to have forward compatible implementations.
type UnimplementedDKVClusterServer struct {
}

func (*UnimplementedDKVClusterServer) AddNode(ctx context.Context, req *AddNodeRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNode not implemented")
}
func (*UnimplementedDKVClusterServer) RemoveNode(ctx context.Context, req *RemoveNodeRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNode not implemented")
}

func RegisterDKVClusterServer(s *grpc.Server, srv DKVClusterServer) {
	s.RegisterService(&_DKVCluster_serviceDesc, srv)
}

func _DKVCluster_AddNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKVClusterServer).AddNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dkv.serverpb.DKVCluster/AddNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKVClusterServer).AddNode(ctx, req.(*AddNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DKVCluster_RemoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKVClusterServer).RemoveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dkv.serverpb.DKVCluster/RemoveNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKVClusterServer).RemoveNode(ctx, req.(*RemoveNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DKVCluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dkv.serverpb.DKVCluster",
	HandlerType: (*DKVClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNode",
			Handler:    _DKVCluster_AddNode_Handler,
		},
		{
			MethodName: "RemoveNode",
			Handler:    _DKVCluster_RemoveNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/serverpb/api.proto",
}
