# run using `goreman -exit-on-error start`

dkv_discovery1:./bin/dkvsrv -listen-addr 127.0.0.1:8001 -node-name d0 -nexus-node-url "http://127.0.0.1:7021" -config clients/java/dkv-client/src/test/resources/discovery_config.json 
dkv_discovery2:./bin/dkvsrv -listen-addr 127.0.0.1:8002 -node-name d1 -nexus-node-url "http://127.0.0.1:7022" -config clients/java/dkv-client/src/test/resources/discovery_config.json 
dkv_discovery3:./bin/dkvsrv -listen-addr 127.0.0.1:8003 -node-name d2 -nexus-node-url "http://127.0.0.1:7023" -config clients/java/dkv-client/src/test/resources/discovery_config.json 

dkv_smaster1:./bin/dkvsrv -listen-addr 127.0.0.1:7080 -node-name m1 -database s0 -config clients/java/dkv-client/src/test/resources/smaster_config.json
dkv_smaster2:./bin/dkvsrv -listen-addr 127.0.0.1:8080 -node-name m2 -database s1 -config clients/java/dkv-client/src/test/resources/smaster_config.json
dkv_smaster3:./bin/dkvsrv -listen-addr 127.0.0.1:9080 -node-name m3 -database s2 -config clients/java/dkv-client/src/test/resources/smaster_config.json

dkv_slave1a:./bin/dkvsrv -listen-addr 127.0.0.1:7091 -database s0 -config clients/java/dkv-client/src/test/resources/slave_config.json 
dkv_slave1b:./bin/dkvsrv -listen-addr 127.0.0.1:7092 -database s0 -config clients/java/dkv-client/src/test/resources/slave_config.json
dkv_slave1c:./bin/dkvsrv -listen-addr 127.0.0.1:7093 -database s0 -config clients/java/dkv-client/src/test/resources/slave_config.json 
dkv_slave1d:./bin/dkvsrv -listen-addr 127.0.0.1:7094 -database s0 -config clients/java/dkv-client/src/test/resources/slave_config.json

dkv_slave2a:./bin/dkvsrv -listen-addr 127.0.0.1:8091 -database s1 -config clients/java/dkv-client/src/test/resources/slave_config.json
dkv_slave2b:./bin/dkvsrv -listen-addr 127.0.0.1:8092 -database s1 -config clients/java/dkv-client/src/test/resources/slave_config.json 
dkv_slave2c:./bin/dkvsrv -listen-addr 127.0.0.1:8093 -database s1 -config clients/java/dkv-client/src/test/resources/slave_config.json
dkv_slave2d:./bin/dkvsrv -listen-addr 127.0.0.1:8094 -database s1 -config clients/java/dkv-client/src/test/resources/slave_config.json 

dkv_slave3a:./bin/dkvsrv -listen-addr 127.0.0.1:9091 -database s2 -config clients/java/dkv-client/src/test/resources/slave_config.json 
dkv_slave3b:./bin/dkvsrv -listen-addr 127.0.0.1:9092 -database s2 -config clients/java/dkv-client/src/test/resources/slave_config.json 
dkv_slave3c:./bin/dkvsrv -listen-addr 127.0.0.1:9093 -database s2 -config clients/java/dkv-client/src/test/resources/slave_config.json 
dkv_slave3d:./bin/dkvsrv -listen-addr 127.0.0.1:9094 -database s2 -config clients/java/dkv-client/src/test/resources/slave_config.json 

dkv_master1:./bin/dkvsrv -listen-addr 127.0.0.1:6080 -node-name s0 -nexus-node-url "http://127.0.0.1:8021" -config clients/java/dkv-client/src/test/resources/master_config.json 
dkv_master2:./bin/dkvsrv -listen-addr 127.0.0.1:6081 -node-name s1 -nexus-node-url "http://127.0.0.1:8022" -config clients/java/dkv-client/src/test/resources/master_config.json   
dkv_master3:./bin/dkvsrv -listen-addr 127.0.0.1:6082 -node-name s2 -nexus-node-url "http://127.0.0.1:8023" -config clients/java/dkv-client/src/test/resources/master_config.json  
