# run using `goreman -exit-on-error start`

dkv_discovery1:./bin/dkvsrv -role discovery -listen-addr 127.0.0.1:8001 -db-folder /tmp/dkvsrv/d0 -discovery-service-config internal/discovery/discovery.ini
dkv_discovery2:./bin/dkvsrv -role discovery -listen-addr 127.0.0.1:8002 -db-folder /tmp/dkvsrv/d1 -discovery-service-config internal/discovery/discovery.ini
dkv_discovery3:./bin/dkvsrv -role discovery -listen-addr 127.0.0.1:8003 -db-folder /tmp/dkvsrv/d2 -discovery-service-config internal/discovery/discovery.ini

dkv_master1:./bin/dkvsrv -role master -listen-addr 127.0.0.1:7080 -db-folder /tmp/dkvsrv/s0 -discovery-service-config internal/discovery/discovery.ini -dc-id dc1 -database s0
dkv_master2:./bin/dkvsrv -role master -listen-addr 127.0.0.1:8080 -db-folder /tmp/dkvsrv/s1 -discovery-service-config internal/discovery/discovery.ini -dc-id dc1 -database s1
dkv_master3:./bin/dkvsrv -role master -listen-addr 127.0.0.1:9080 -db-folder /tmp/dkvsrv/s2 -discovery-service-config internal/discovery/discovery.ini -dc-id dc1 -database s2

dkv_slave1a:./bin/dkvsrv -diskless -db-engine badger -role slave -listen-addr 127.0.0.1:7091 -repl-poll-interval 2s -discovery-service-config internal/discovery/discovery.ini -dc-id dc1 -database s0 -disable-auto-master-disc=false
dkv_slave1b:./bin/dkvsrv -diskless -db-engine badger -role slave -listen-addr 127.0.0.1:7092 -repl-poll-interval 2s -discovery-service-config internal/discovery/discovery.ini -dc-id dc1 -database s0 -disable-auto-master-disc=false
dkv_slave1c:./bin/dkvsrv -diskless -db-engine badger -role slave -listen-addr 127.0.0.1:7093 -repl-poll-interval 2s -discovery-service-config internal/discovery/discovery.ini -dc-id dc1 -database s0 -disable-auto-master-disc=false
dkv_slave1d:./bin/dkvsrv -diskless -db-engine badger -role slave -listen-addr 127.0.0.1:7094 -repl-poll-interval 2s -discovery-service-config internal/discovery/discovery.ini -dc-id dc1 -database s0 -disable-auto-master-disc=false

dkv_slave2a:./bin/dkvsrv -diskless -db-engine badger -role slave -listen-addr 127.0.0.1:8091 -repl-poll-interval 2s -discovery-service-config internal/discovery/discovery.ini -dc-id dc1 -database s1 -disable-auto-master-disc=false
dkv_slave2b:./bin/dkvsrv -diskless -db-engine badger -role slave -listen-addr 127.0.0.1:8092 -repl-poll-interval 2s -discovery-service-config internal/discovery/discovery.ini -dc-id dc1 -database s1 -disable-auto-master-disc=false
dkv_slave2c:./bin/dkvsrv -diskless -db-engine badger -role slave -listen-addr 127.0.0.1:8093 -repl-poll-interval 2s -discovery-service-config internal/discovery/discovery.ini -dc-id dc1 -database s1 -disable-auto-master-disc=false
dkv_slave2d:./bin/dkvsrv -diskless -db-engine badger -role slave -listen-addr 127.0.0.1:8094 -repl-poll-interval 2s -discovery-service-config internal/discovery/discovery.ini -dc-id dc1 -database s1 -disable-auto-master-disc=false

dkv_slave3a:./bin/dkvsrv -diskless -db-engine badger -role slave -listen-addr 127.0.0.1:9091 -repl-poll-interval 2s -discovery-service-config internal/discovery/discovery.ini -dc-id dc1 -database s2 -disable-auto-master-disc=false
dkv_slave3b:./bin/dkvsrv -diskless -db-engine badger -role slave -listen-addr 127.0.0.1:9092 -repl-poll-interval 2s -discovery-service-config internal/discovery/discovery.ini -dc-id dc1 -database s2 -disable-auto-master-disc=false
dkv_slave3c:./bin/dkvsrv -diskless -db-engine badger -role slave -listen-addr 127.0.0.1:9093 -repl-poll-interval 2s -discovery-service-config internal/discovery/discovery.ini -dc-id dc1 -database s2 -disable-auto-master-disc=false
dkv_slave3d:./bin/dkvsrv -diskless -db-engine badger -role slave -listen-addr 127.0.0.1:9094 -repl-poll-interval 2s -discovery-service-config internal/discovery/discovery.ini -dc-id dc1 -database s2 -disable-auto-master-disc=false

