;;;----------------------------------------------------------------------------------
;;; Generated by protoc-gen-clojure.  DO NOT EDIT
;;;
;;; GRPC dkv.serverpb.DKVBackupRestore Client Implementation
;;;----------------------------------------------------------------------------------
(ns dkv.serverpb.DKVBackupRestore.client
  (:require [dkv.serverpb :refer :all]
            [clojure.core.async :as async]
            [protojure.grpc.client.utils :refer [send-unary-params invoke-unary]]
            [promesa.core :as p]
            [protojure.grpc.client.api :as grpc]))

;-----------------------------------------------------------------------------
; GRPC Client Implementation
;-----------------------------------------------------------------------------

(defn Backup
  [client params]
  (let [input (async/chan 1)
        output (async/chan 1)
        desc {:service "dkv.serverpb.DKVBackupRestore"
              :method  "Backup"
              :input   {:f dkv.serverpb/new-BackupRequest :ch input}
              :output  {:f dkv.serverpb/pb->Status :ch output}}]
    (-> (send-unary-params input params)
        (p/then (fn [_] (invoke-unary client desc output))))))

(defn Restore
  [client params]
  (let [input (async/chan 1)
        output (async/chan 1)
        desc {:service "dkv.serverpb.DKVBackupRestore"
              :method  "Restore"
              :input   {:f dkv.serverpb/new-RestoreRequest :ch input}
              :output  {:f dkv.serverpb/pb->Status :ch output}}]
    (-> (send-unary-params input params)
        (p/then (fn [_] (invoke-unary client desc output))))))

