{
 "title": "Dkv Slave Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Store Latency - Save",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "storage_latency{ops=\"saveChange\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Store Latency - GET",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "storage_latency{ops=\"get\"}",
     "legendFormat": " {{quantile}} "
    }
   ]
  },
  {
   "title": "Slave Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "slave_replication_lag", "legendFormat": "ip: {{instance}}" }
   ]
  },
  {
   "title": "Operations One Minute Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(storage_latency_count[1m])",
     "legendFormat": "{{ops}}"
    }
   ]
  },
  {
   "title": "Storage Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "rate(storage_error)" }
   ]
  }
 ]
}