;;;----------------------------------------------------------------------------------
;;; Generated by protoc-gen-clojure.  DO NOT EDIT
;;;
;;; GRPC dkv.serverpb.DKVReplication Client Implementation
;;;----------------------------------------------------------------------------------
(ns dkv.serverpb.DKVReplication.client
  (:require [dkv.serverpb :refer :all]
            [clojure.core.async :as async]
            [protojure.grpc.client.utils :refer [send-unary-params invoke-unary]]
            [promesa.core :as p]
            [protojure.grpc.client.api :as grpc]))

;-----------------------------------------------------------------------------
; GRPC Client Implementation
;-----------------------------------------------------------------------------

(defn GetChanges
  [client params]
  (let [input (async/chan 1)
        output (async/chan 1)
        desc {:service "dkv.serverpb.DKVReplication"
              :method  "GetChanges"
              :input   {:f dkv.serverpb/new-GetChangesRequest :ch input}
              :output  {:f dkv.serverpb/pb->GetChangesResponse :ch output}}]
    (-> (send-unary-params input params)
        (p/then (fn [_] (invoke-unary client desc output))))))

