{
 "title": "DKV Master Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Latency Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PUT Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "dkv_latency{role=\"master\", Ops=\"put\",quantile=\"0.5\"}",
     "legendFormat": "50p"
    },
    {
     "expr": "dkv_latency{role=\"master\", Ops=\"put\",quantile=\"0.9\"}",
     "legendFormat": "90p"
    },
    {
     "expr": "dkv_latency{role=\"master\", Ops=\"put\",quantile=\"0.99\"}",
     "legendFormat": "99p"
    }
   ]
  },
  {
   "title": "ITER Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "dkv_latency{role=\"master\", Ops=\"iter\",quantile=\"0.5\"}",
     "legendFormat": "50p"
    },
    {
     "expr": "dkv_latency{role=\"master\", Ops=\"iter\",quantile=\"0.9\"}",
     "legendFormat": "90p"
    },
    {
     "expr": "dkv_latency{role=\"master\", Ops=\"iter\",quantile=\"0.99\"}",
     "legendFormat": "99p"
    }
   ]
  },
  { "title": "Count Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "PUT One Minute Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dkv_latency_count{role=\"master\", Ops=\"put\"}"
    }
   ]
  },
  {
   "title": "ITER Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dkv_latency_count{role=\"master\", Ops=\"iter\"}"
    }
   ]
  },
  {
   "title": "PUT One Minute Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(dkv_latency_count{role=\"master\", Ops=\"put\"}[1m])"
    }
   ]
  },
  {
   "title": "ITER One Minute Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(dkv_latency_count{role=\"master\", Ops=\"iter\"}[1m])"
    }
   ]
  }
 ]
}