{
 "title": "Dkv Slave Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Count Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Save Changes Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storage_latency_count{role=\"slave\", ops=\"saveChange\"}"
    }
   ]
  },
  {
   "title": "GET Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storage_latency_count{role=\"slave\", ops=\"get\"}"
    }
   ]
  },
  {
   "title": "Operations One Minute Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(storage_latency_count{role=\"slave\", ops=\"get\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(storage_latency_count{role=\"slave\", ops=\"saveChange\"}[1m])",
     "legendFormat": "Save Change"
    }
   ]
  },
  { "title": "Error Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Slave Replication Lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "slave_replication_delay", "legendFormat": "ip: {{instance}}" }
   ]
  },
  {
   "title": "Storage Error",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "storage_error" }
   ]
  },
  { "title": "Latency Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Store Latency - GET",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "storage_latency{ops=\"get\",role=\"slave\"}",
     "legendFormat": " {{quantile}}p"
    }
   ]
  },
  {
   "title": "Store Latency - Save",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "storage_latency{ops=\"saveChange\", role=\"slave\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}